[build]
  command = "corepack enable && corepack prepare pnpm@8.15.0 --activate && pnpm install --frozen-lockfile=false && cd apps/web && pnpm run build"
  publish = "apps/web/.next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18.17.0"
  PNPM_VERSION = "8.15.0"
